version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lastest
    steps:
      - checkout
      - run: echo "npm installing..."
      - run: npm install
      - CI=true npm run build
  test:
    docker:
      - image: circle/node:lastest
    steps:
      - checkout
      - run: echo "testing..."
      - run: npm install
      - run: npm test
  hithere:
    docker:
      - image: circle/node:lastest
    steps:
      - checkout
      - run: echo "Hello..."

workflows:
  version: 2
    build_test_and_lint:
      jobs:
        - build
        - hithere
        - test
          requires:
            - hithere