version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node@2.0.2
    steps:
      - checkout
      - run: echo "npm installing..."
      - run: npm install
      - run: npm run build
  test:
    docker:
      - image: circleci/node@2.0.2
    steps:
      - checkout
      - run: echo "testing..."
      - run: npm test

workflows:
    build_and_test:
      jobs:
        - build
        - test