version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lastest
    steps:
      - checkout
      - run: echo "npm installing..."
      - run: npm install
      - Crun: npm run build
  test:
    docker:
      - image: circle/node:lastest
    steps:
      - checkout
      - run: echo "testing..."
      # - run: npm install
      - run: npm test

workflows:
    build_and_test:
      jobs:
        - build
        - test